create table public.pokemons
(
    id        bigint generated by default as identity not null,
    name      character varying null,
    image_url character varying null,
    wins      bigint null,
    losses    bigint null,
    constraint pokemons_pkey primary key (id)
) TABLESPACE pg_default;